//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EGGSAS.rc
//
#define IDC_PAUSE_STUDY                 3
#define IDC_BTN_SET_RESP                3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_LOCAL_DB                    101
#define IDR_MAINFRAME                   128
#define IDR_EGGSASTYPE                  129
#define IDR_MAINFRAME1                  129
#define IDD_10MIN_VIEW                  140
#define IDD_DEMOGRAPHICS                141
#define IDD_EQUIP_TEST                  142
#define IDI_GREEN_LED                   144
#define IDI_RED_LED                     145
#define IDD_BASELINE                    146
#define IDD_WATER_LOAD                  147
#define IDD_POST_WATER_TEST             148
#define IDD_PRE_STUDY_INFO              149
#define IDD_SELECT_PATIENT              151
#define IDD_DIAGNOSTIC_HISTORY          153
#define IDD_MEDICATIONS                 154
#define IDD_DIAGNOSIS                   155
#define IDD_FACILITY_INFO               159
#define IDD_RECOMMENDATIONS             160
#define IDD_CUSTOM_REPORT               162
#define IDD_RESPIRATION                 164
#define IDD_EDIT_VIEW_RESPIRATION       165
#define IDD_BCKUP_REST                  166
#define IDB_3CPM_LOGO                   167
#define IDD_STIMULATION_MEDIUM          167
#define IDB_BITMAP1                     172
#define IDD_FINISH_STUDY                173
#define IDD_SELECT_STUDY_TYPE           174
#define IDD_CHG_MIN_PER_GRAPH           175
#define IDD_EDIT_VIEW_RESP_RESEARCH     176
#define IDD_EVENT_RECORDER              178
#define IDD_EVENT_LIST                  179
#define IDD_WHAT_IF                     180
#define IDD_IMPORT_REMOTE_DB            181
#define IDD_BCKUP_REST_ERRS             182
#define IDD_SETTINGS                    183
#define IDD_FREQ_RANGE                  185
#define IDI_ICON1                       187
#define IDI_ICON2                       188
#define IDD_FILTER_RSA                  189
#define IDD_SEL_STUDY_TYPE_FREQ         190
#define IDD_HIDE_STUDY_DATE             191
#define IDD_SEARCH                      192
#define IDD_IMPORT_DUP_NAME             193
#define IDC_PATIENT_NAME                1000
#define IDC_FIRST_4_MIN                 1001
#define IDC_PATIENT_LAST_NAME           1001
#define IDC_STUDY_TYPE                  1001
#define IDC_SECOND_4_MIN                1002
#define IDC_EDIT1                       1002
#define IDC_RESP_RATE_10                1002
#define IDC_MIDDLE_INITIAL              1002
#define IDC_EDIT_MIN_PER_GRAPH          1002
#define IDC_EDIT_RESPIRATION            1002
#define IDC_EDIT_EVENT_DESCRIPTION      1002
#define IDC_EDIT_WHAT_IF_DESCRIPTION    1002
#define IDC_EDIT_WHAT_IF                1002
#define IDC_EDIT_DB_LOCATION            1002
#define IDC_EDIT_DATA_FILE_LOC          1002
#define IDC_EDIT_FAC_LOGO               1002
#define IDC_EDIT_PASSWORD               1002
#define IDC_EDIT_NAME_RRNUM             1002
#define IDC_EDIT_NAME                   1002
#define IDC_THIRD_4_MIN                 1003
#define IDC_RESP_RATE_20                1003
#define IDC_EDIT_MONTH                  1003
#define IDC_EDIT_REMOTE_DB_LOC          1003
#define IDC_ADDRESS1                    1004
#define IDC_RESP_RATE_30                1004
#define IDC_EDIT_DAY                    1004
#define IDC_ADDRESS2                    1005
#define IDC_RESP_RATE_40                1005
#define IDC_EDIT_YEAR                   1005
#define IDC_CITY                        1006
#define IDC_STATE                       1007
#define IDC_ZIPCODE                     1008
#define IDC_PHONE_NUMBER                1009
#define IDC_HOSPITAL_NUMBER             1010
#define IDC_DATE_OF_BIRTH               1011
#define IDC_SOCIAL_SECURITY_NUM         1012
#define IDC_RESRCH_REF_NUM_ENA          1013
#define IDC_RESRCH_REF_NUM              1014
#define IDC_SAVE                        1015
#define IDC_SAVE_AND_CLOSE              1015
#define IDC_10MIN_PERIOD_LST            1016
#define IDC_RESP_GREEN                  1017
#define IDC_ELECTRODE_RED               1018
#define IDC_ELECTRODE_GREEN             1019
#define IDC_RESP_RED                    1020
#define IDC_START_TEST                  1021
#define IDC_START_BL                    1022
#define IDC_CLOCK                       1023
#define IDC_BEGIN_WATER                 1024
#define IDC_EXTEND                      1024
#define IDC_WATER_AMOUNT                1025
#define IDC_OUNCES                      1026
#define IDC_MILLILITERS                 1027
#define IDC_START                       1028
#define IDC_GRAMS                       1028
#define IDC_EXTEND_TEST                 1029
#define IDC_DEMO_TEXT                   1030
#define IDC_MEAL_TIME                   1031
#define IDC_PATIENT_DB_LIST             1033
#define IDC_IMPORT                      1034
#define IDC_ALTERNATE_DB                1035
#define IDC_ACCEPT                      1036
#define IDC_BTN_SELECT_READER_DB        1036
#define IDC_REJECT                      1037
#define IDC_BTN_SELECT_LOCAL_DB         1037
#define IDC_START_MIN                   1038
#define IDC_END_MIN                     1039
#define IDC_SELECT_NEW_MINUTES          1040
#define IDC_START_MIN_TITLE             1041
#define IDC_END_MIN_TITLE               1042
#define IDC_GOOD_MIN                    1043
#define IDC_SELECT_PERIOD_LEN           1044
#define IDC_START_PERIOD_MIN_TITLE      1045
#define IDC_START_PERIOD_MIN            1046
#define IDC_END_PERIOD_MIN_TITLE        1047
#define IDC_ADD_DIAGNOSIS               1048
#define IDC_END_PERIOD_MIN              1048
#define IDC_DELETE_DIAGNOSIS            1049
#define IDC_SELECT_GOOD_MINUTES         1049
#define IDC_REPLACE_DIAGNOSIS           1050
#define IDC_GOTO_STUDY                  1050
#define IDC_START_GOOD_MIN_TITLE        1050
#define IDC_DIAGNOSIS                   1051
#define IDC_START_GOOD_MIN              1051
#define IDC_DIAGNOSIS_LIST              1052
#define IDC_END_GOOD_MIN_TITLE          1052
#define IDC_END_GOOD_MIN                1053
#define IDC_EVENT_DESCRIPTION           1054
#define IDC_DIAGNOSIS_DATE              1055
#define IDC_EVENT_DESC_TITLE            1055
#define IDC_MEDICATION_LIST             1056
#define IDC_STATIC_WHAT_IF              1056
#define IDC_MEDICATION_DATE             1057
#define IDC_MEDICATION                  1058
#define IDC_ADD_MEDICATION              1059
#define IDC_REPLACE_MEDICATION          1060
#define IDC_DELETE_MEDICATION           1061
#define IDC_DATE_TITLE                  1062
#define IDC_DIAGNOSIS_TITLE             1063
#define IDC_MEDICATION_TITLE            1064
#define IDC_ANALYZE_TITLE               1065
#define IDC_SUGGESTED_DIAGNOSIS         1066
#define IDC_ACCEPT_DIAGNOSIS            1067
#define IDC_MODIFY_DIAGNOSIS            1068
#define IDC_REJECT_DIAGNOSIS            1069
#define IDC_ARTIFACT_LIST               1070
#define IDC_PATIENT_FIRST_NAME          1071
#define IDC_EVENT_LIST                  1071
#define IDC_DEBUG                       1072
#define IDC_DATE                        1073
#define IDC_IFP_NAUSEA                  1074
#define IDC_IFP_VOMITING                1075
#define IDC_IFP_BLOATING                1076
#define IDC_IFP_POST_PRANDIAL_FULLNESS  1077
#define IDC_IFP_EARLY_SATEITY           1078
#define IDC_IFP_GERD                    1079
#define IDC_IFP_ERUCTUS                 1080
#define IDC_IFP_COMMENTS_TITLE          1081
#define IDC_IFP_COMMENTS                1082
#define IDC_ATTEND_PHYS                 1083
#define IDC_REFER_PHYS                  1084
#define IDC_MED_DATE                    1084
#define IDC_TECHNICIAN                  1085
#define IDC_MED_UPDATE                  1085
#define IDC_MED_GOTO_STUDY              1086
#define IDC_CHK_GASTROPARESIS           1086
#define IDC_FACILITY_NAME               1087
#define IDC_CHK_DYSPEPSIA_BLOAT_SATIETY 1087
#define IDC_FACILITY_ADDRESS1           1088
#define IDC_CHK_POST_DILATION_EVAL      1088
#define IDC_FACILITY_ADDRESS2           1089
#define IDC_CHK_EVAL_EFFECT_MED         1089
#define IDC_FACILITY_CITY               1090
#define IDC_FACILITY_ZIPCODE            1091
#define IDC_CHK_DYSPEPSIA               1091
#define IDC_FACILITY_PHONE              1092
#define IDC_CHK_REFRACTORY_GERD         1092
#define IDC_FACILITY_STATE              1093
#define IDC_CHK_ANOREXIA                1093
#define IDC_RECOMMENDATIONS             1094
#define IDC_CHK_WEIGHTLOSS              1094
#define IDC_RPT_ENTIRE_RAW_SIGNAL       1095
#define IDC_RPT_DATA_SHEET              1096
#define IDC_CORE_REPORT                 1097
#define IDC_RESP_RATE                   1098
#define IDC_RPT_EVENT_LOG               1098
#define IDC_ARTIFACT_TITLE              1099
#define IDC_GOOD_MIN_TITLE              1100
#define IDC_START_MIN_SPIN              1102
#define IDC_END_MIN_SPIN                1103
#define IDC_UNDO_CHANGES                1104
#define IDC_SAVE_CHANGES                1105
#define IDC_ACCEPT_CHANGES              1105
#define IDC_SUGGESTED_MIN_FRAME         1106
#define IDC_START_PERIOD_MIN_SPIN       1107
#define IDC_PERIOD                      1108
#define IDC_END_PERIOD_MIN_SPIN         1108
#define IDC_BACKUP                      1109
#define IDC_DELETE_THIS_PERIOD          1109
#define IDC_RESET_PERIODS               1109
#define IDC_RESTORE                     1110
#define IDC_INSERT_NEW_PERIOD           1110
#define IDC_PROGRESS1                   1111
#define IDC_START_GOOD_MIN_SPIN         1111
#define IDC_BCKUP_REST_PROG_TITLE       1112
#define IDC_END_GOOD_MIN_SPIN           1112
#define IDC_BCKUP_REST_PATH             1113
#define IDC_PERIOD_GOOD_MIN_FRAME       1113
#define IDC_BCKUP_REST_TOFROM           1114
#define IDC_FRAME_PERIOD_EVENT          1114
#define IDC_BTN_EVENTS_EDIT             1115
#define IDC_BCKUP_REST_FILENAME         1116
#define IDC_BTN_EVENTS_DELETE           1116
#define IDC_FILE_COPIED                 1117
#define IDC_RESP_4_TITLE                1118
#define IDC_PROGRAM_NAME                1119
#define IDC_VERSION                     1120
#define IDC_COPYRIGHT                   1121
#define IDC_COPYRIGHT1                  1122
#define IDC_STATUS                      1123
#define IDC_EXPIRE                      1123
#define IDC_LOGO_3CPM                   1124
#define IDC_ADJUST_AMP                  1127
#define IDC_INC_AMP_TITLE               1128
#define IDC_DEC_AMP_TITLE               1129
#define IDC_ADJUST_FREQ                 1130
#define IDC_INC_FREQ_TITLE              1131
#define IDC_DEC_FREQ_TITLE              1132
#define IDC_EQUIP_TEST_HELP             1134
#define IDC_BASELINE_HELP               1135
#define IDC_POSTWATER_HELP              1137
#define IDC_BUTTON1                     1138
#define IDC_CONFIGRPT_HELP              1138
#define IDC_DEMOGRAPHICS_HELP           1138
#define IDC_DIAGNOSIS_HELP              1138
#define IDC_DIAGHIST_HELP               1138
#define IDC_EDITVIEWRESP_HELP           1138
#define IDC_FACILITYINFO_HELP           1138
#define IDC_MEDICATIONS_HELP            1138
#define IDC_PRESTUDY_HELP               1138
#define IDC_RECOMMENDATIONS_HELP        1138
#define IDC_SELECTPATIENT_HELP          1138
#define IDC_WATERLOAD_HELP              1138
#define IDC_SKIP_STIM_MED               1138
#define IDC_BTN_RECALL                  1138
#define IDC_BTN_IMPORT                  1138
#define IDC_DATA_FILE_LOC_BROWSE        1138
#define IDC_BUTTON_NEW_PASSWORD         1138
#define IDC_BCKUPREST_HELP              1139
#define IDC_BTN_DELETE                  1139
#define IDC_BTN_BROWSE                  1139
#define IDC_SETTINGS_HELP               1139
#define IDC_RPT_RSA                     1140
#define IDC_BTN_WHAT_IF_HELP            1140
#define IDC_IMPORT_REMOTE_DB_HELP       1140
#define IDC_RPT_RSA_FIRST_PAGE          1140
#define IDC_REMOTE_DB_LOC_BROWSE        1140
#define IDC_RPT_SUMM_GRAPHS             1141
#define IDC_BTN_SAVE                    1141
#define IDC_RPT_RAW_SIG_SEL_MIN         1142
#define IDC_BTN_SELECT_ALL              1142
#define IDC_RPT_DIAG_RECOM              1143
#define IDC_DELAYED_GASTRIC_EMPTYING    1144
#define IDC_RPT_PATIENT_INFO            1144
#define IDC_PRODUCT_OF                  1145
#define IDC_RPT_RSA_OTHER_PAGE          1145
#define IDC_VISISPACE_LOGO              1146
#define IDC_RPT_SUMM_GRPHS_FIRST_PAGE   1146
#define IDC_EDIT_QUANTITY               1147
#define IDC_RPT_SUMM_GRPHS_OTHER_PAGE   1147
#define IDC_EDIT_DESCRIPTION            1148
#define IDC_RPT_RSA_INCLUDE_BOTH        1148
#define IDC_BEGIN_STIM_MEDIUM           1149
#define IDC_FINISH_STUDY                1150
#define IDC_SCROLLBAR_GRAPH             1151
#define IDC_CHK_SET_PERIOD_LENGTH       1152
#define IDC_CHK_SET_GOOD_MINUTES        1153
#define IDC_CHK_STANDARD                1153
#define IDC_CHK_RESEARCH                1154
#define IDC_TITLE                       1155
#define IDC_LIST_RESPIRATION            1156
#define IDC_CHK_RESEARCH_60             1156
#define IDC_CHK_RESEARCH_200            1157
#define IDC_CHK_COUGH                   1158
#define IDC_CHK_MOVEMENT                1159
#define IDC_CHK_TALKING                 1160
#define IDC_CHK_INGESTION               1161
#define IDC_CHK_NAUSEA                  1162
#define IDC_CHK_PAIN                    1163
#define IDC_CHK_VOMITING                1164
#define IDC_CHK_OTHER                   1165
#define IDC_EDIT_TIME                   1167
#define IDC_LIST_EVENTS                 1168
#define IDC_LIST2                       1170
#define IDC_LIST_WHAT_IF                1170
#define IDC_STATIC_DATE_TIME            1174
#define IDC_STATIC_DESCRITPION          1175
#define IDC_STATIC_DB_FILE              1175
#define IDC_CHK_HUMAN                   1178
#define IDC_CHK_DOG                     1179
#define IDC_DATETIMEPICKER1             1180
#define IDC_DATETIMEPICKER_MEAL         1180
#define IDC_CHK_MALE                    1180
#define IDC_STATIC_PROGRESS_TITLE       1181
#define IDC_CHK_FEMALE                  1181
#define IDC_LIST_IMPORT                 1182
#define IDC_CHK_HIDE                    1182
#define IDC_LIST_ERRORS                 1183
#define IDC_STATIC_NUM_ERRS             1184
#define IDC_STATIC_CURRENT_DB           1185
#define IDC_STATIC_PATIENT_NAME         1186
#define IDC_STATIC_MIDDLE_INITIAL       1187
#define IDC_STATIC_LAST_NAME            1188
#define IDC_STATIC_DATE_OF_BIRTH        1189
#define IDC_STATIC_DATE_FMT             1190
#define IDC_STATIC_SSN                  1191
#define IDC_STATIC_ADDRESS              1192
#define IDC_STATIC_ADDRESS_1            1193
#define IDC_STATIC_CITY                 1194
#define IDC_STATIC_STATE                1195
#define IDC_STATIC_ZIP_CODE             1196
#define IDC_STATIC_PHONE_NUM            1197
#define IDC_STATIC_HOSP_NUM             1198
#define IDC_STATIC_MEAL_TIME            1199
#define IDC_STATIC_BOX_INDICATIONS      1200
#define IDC_STATIC_ATTENDING_PHYSICIAN  1201
#define IDC_STATIC_REFERRING_PHYSICIAN  1202
#define IDC_STATIC_TECHNICIAN           1203
#define IDC_STATIC_RESPIRATORY_SENSOR   1204
#define IDC_STATIC_GASTRIC_ELECTRODES   1205
#define IDC_STATIC_IMPORT_DB_FROM       1206
#define IDC_STATIC_INSTRUCTIONS         1207
#define IDC_STATIC_SUGGESTED_DIAGNOSIS  1208
#define IDC_STATIC_INSTRUCTIONS2        1208
#define IDC_STATIC_DIAGNOSIS            1209
#define IDC_STATIC_CHANGE_RESP          1210
#define IDC_STATIC_FIRST_10_MIN_PD      1211
#define IDC_STATIC_SECOND_10_MIN_PD     1212
#define IDC_STATIC_THIRD_10_MIN_PD      1213
#define IDC_STATIC_DESCRIPTION          1214
#define IDC_STATIC_TIME                 1215
#define IDC_STATIC_PRACTICE_NAME        1216
#define IDC_STATIC_ADDRESS1             1217
#define IDC_STATIC_ZIPCODE              1218
#define IDC_STATIC_PHONE                1219
#define IDC_STATIC_QUANTITY             1220
#define IDC_STATIC_AMT_WATER            1221
#define IDC_STATIC_DESCRIPTION_1        1222
#define IDC_COMBO_LANGUAGE              1223
#define IDC_STATIC_SEL_LANGUAGE         1224
#define IDC_STATIC_DATA_FILE_LOC        1225
#define IDC_BTN_ADD_TO_REPORT           1226
#define IDC_STATIC_REMOTE_DB_LOC        1226
#define IDC_BTN_INCLUDE_ICD_CODE        1227
#define IDC_STATIC_REMOTE_DB_PASSWD     1227
#define IDC_CBX_RECOMM_KEY_PHRASE       1228
#define IDC_CBX_ICD_LIST                1229
#define IDC_BTN_SAVE_DIAG_TO_LIST       1230
#define IDC_BTN_REMOVE_FROM_LIST        1231
#define IDC_BTN_SAVE_ICD_TO_LIST        1232
#define IDC_CHK_FAC_NAME                1232
#define IDC_BTN_REMOVE_ICD_FROM_LIST    1233
#define IDC_CHK_FAC_ADDR1               1233
#define IDC_CHK_FAC_ADDR2               1234
#define IDC_CHK_FAC_CITY                1235
#define IDC_CHK_FAC_STATE               1236
#define IDC_CHK_FAC_ZIPCODE             1237
#define IDC_CHK_FAC_PHONENUM            1238
#define IDC_CHK_INCRPT_ADDR2            1239
#define IDC_BTN_BROWSE_LOGO             1239
#define IDC_CHK_FAC_LOGO                1240
#define IDC_CHK_INCRPT_ZIPCODE          1241
#define IDC_CHK_INCRPT_STATE            1242
#define IDC_CHK_INCRPT_PHONENUM         1243
#define IDC_CHK_INCRPT_HOSPNUM          1244
#define IDC_CHK_INCRPT_RSRCHREFNUM      1245
#define IDC_CHK_INCRPT_FIRSTNAME        1246
#define IDC_CHK_INCRPT_MI               1247
#define IDC_CHK_INCRPT_LASTNAME         1248
#define IDC_CHK_INCRPT_DATEOFBIRTH      1249
#define IDC_CHK_INCRPT_SSN              1250
#define IDC_CHK_INCRPT_ADDR1            1251
#define IDC_CHK_INCRPT_CITY             1252
#define IDC_STATIC_INC_IN_RPT_DESC      1253
#define IDC_STATIC_FAC_INC_IN_RPT_DESC  1254
#define IDC_CHK_INCRPT_MALE_FEMALE      1254
#define IDC_STATIC_RSA_TITLE            1255
#define IDC_STATIC_SUMM_GRPHS_TITLE     1256
#define IDC_CBX_DIAG_LIST               1257
#define IDC_STATIC_ADDITIONAL_FEATURE_INFO 1258
#define IDC_STATIC_LOGO_REQ             1259
#define IDC_STATIC_LOGO_REQ2            1260
#define IDC_BTN_SAVE_RECOMM_TO_LIST     1260
#define IDC_STATIC_LOGO_REQ3            1261
#define IDC_CHK_15_CPM                  1261
#define IDC_STATIC_LOGO_REQ4            1262
#define IDC_CHK_60_CPM                  1262
#define IDC_CHK_ATTEND_PHYS             1262
#define IDC_CHK_200_CPM                 1263
#define IDC_CHK_REFER_PHYS              1263
#define IDC_STATIC_SEL_FREQ_RANGE       1263
#define IDC_CHK_TECHNICIAN              1264
#define IDC_RADIO_15_CPM                1264
#define IDC_RADIO_60_CPM                1265
#define IDC_RADIO_200_CPM               1266
#define IDC_CHK_FILTER                  1267
#define IDC_FREQ_RANGE_HELP             1268
#define IDC_CHK_STANDARD_15             1269
#define IDC_CHK_RESEARCH_15             1270
#define IDC_STATIC_ENTER_PASSWORD       1273
#define IDC_BUTTON_RESET_PASSWORD       1274
#define IDC_STATIC_ENTER_NEW_PASSWORD   1275
#define IDC_EDIT_NEW_PASSWORD           1276
#define IDC_BUTTON_NEXT                 1277
#define IDC_STATIC_VALIDATE_PASSWORD    1278
#define IDC_EDIT_VALIDATE_PASSWORD      1279
#define IDC_EDIT_HIDE_SHOW_STATE        1281
#define IDC_EDIT_RESET_PASSWORD         1282
#define IDC_CHK_NAME_ASC                1284
#define IDC_CHK_NAME_DESC               1285
#define IDC_CHK_DATE_OLDER              1288
#define IDC_CHK_DATE_NEWER              1289
#define IDC_CHK_DATE_EQUAL              1290
#define IDC_CHK_LAST_NAME               1295
#define IDC_CHK_RRNUM                   1296
#define IDC_STATIC_NAME_RRNUM           1297
#define IDC_STATIC_STUDY_DATE           1298
#define IDC_STATIC_LABEL_NAME           1299
#define IDC_STATIC_NAME_HELP            1300
#define IDC_STATIC_LABEL_DATE           1301
#define IDC_STATIC_MONTH_HELP           1302
#define IDC_STATIC_DAY_HELP             1303
#define IDC_STATIC_YEAR_HELP            1304
#define IDC_STATIC_DATE_HELP            1305
#define IDC_BTN_SEARCH                  1306
#define IDC_SEARCH_HELP                 1307
#define IDC_RADIO_SKIP                  1308
#define IDC_RADIO_OVERWRITE             1309
#define IDC_RADIO_CHANGE_NAME           1310
#define IDC_STATIC_NAME                 1311
#define IDC_STATIC_NAME2                1312
#define IDC_STATIC_TITLE                1312
#define IDC_EDIT_REMOTE_DB_PASSWD       1312
#define ID_FILE_REV_ORIG                32771
#define ID_FILE_NEW_PATIENT             32772
#define ID_FILE_EXIST_PATIENT           32773
#define ID_EDIT_PATIENT_DIAG_HIST       32774
#define ID_EDIT_PATIENT_MEDS            32775
#define ID_EDIT_SUGGESTED_DIAG          32776
#define ID_VIEW_PATIENT_DIAG_HIST       32777
#define ID_VIEW_PATIENT_MEDS            32778
#define ID_VIEW_SUGGESTED_DIAG          32779
#define ID_VIEW_BASELINE                32780
#define ID_VIEW_POSTWATER_10            32781
#define ID_VIEW_POSTWATER_20            32782
#define ID_VIEW_POSTWATER_30            32783
#define ID_GOTO_PREV_PERIOD             32784
#define ID_GOTO_NEXT_PERIOD             32785
#define ID_GOTO_START                   32786
#define ID_GOTO_END                     32787
#define ID_ANALYZE_BASELINE             32788
#define ID_ANALYZE_POSTWATER_10         32789
#define ID_ANALYZE_POSTWATER_20         32790
#define ID_ANALYZE_POSTWATER_30         32791
#define ID_ANALYZE_CURRENT              32792
#define ID_ANALYZE_DIAGNOSIS            32793
#define ID_REPORT_CREATE                32794
#define ID_REPORT_CONFIGURE1            32794
#define ID_REPORT_VIEW                  32795
#define ID_REPORT_DELETE                32796
#define ID_REPORT_EDIT                  32797
#define ID_REPORT_TYPE                  32798
#define ID_REPORT_BASELINE              32799
#define ID_REPORT_POSTWATER_10          32800
#define ID_REPORT_POSTWATER_20          32801
#define ID_REPORT_POSTWATER_30          32802
#define ID_REPORT_DIAGNOSIS             32803
#define ID_REPORT_RECOMMENDATIONS       32804
#define ID_REPORT_CORE_EGG              32805
#define ID_REPORT_CUSTOM                32806
#define IDW_COMBO                       32807
#define IDS_ENTER_WATER_AMOUNT          32808
#define IDS_OK                          32809
#define IDS_END_STUDY_ARE_YOU_SURE      32810
#define IDS_WARNING                     32811
#define ID_EDIT_PRE_STUDY_INFO          32813
#define ID_VIEW_PRE_STUDY_INFO          32814
#define IDS_TITLE_10_MIN_PERIOD         32815
#define ID_EDIT_PATIENT_DEMOGRAHICS     32815
#define IDS_TITLE_20_MIN_PERIOD         32816
#define ID_VIEW_PATIENT_DEMOGRAHICS     32816
#define IDS_TITLE_30_MIN_PERIOD         32817
#define ID_VIEW_AMT_WATER               32817
#define ID_EDIT_AMT_WATER               32818
#define IDS_ERROR                       32819
#define ID_ANALYZE_RSA                  32819
#define IDS_ERR_POSITION_FILE           32820
#define IDS_ERR_READ_FILE               32821
#define ID_REPORT_PRINT                 32821
#define IDS_ERR_UNEXPECTED_EOF          32822
#define ID_REPORT_FAC_INFO              32822
#define IDS_ERR_OPEN_FILE               32823
#define ID_ANALYZE_POSTWATER_40         32823
#define ID_REPORT_POSTWATER_40          32823
#define IDS_NO_DATA_IN_FILE             32824
#define ID_VIEW_POSTWATER_40            32824
#define ID_EDIT_RECOMMENDATIONS         32825
#define ID_VIEW_RECOMMENDATIONS         32826
#define IDS_SAVE_CLOSE                  32827
#define IDS_TITLE_BASELINE              32828
#define IDS_RAW_WAVFRM_Y_AXIS_LBL       32829
#define IDS_ERR_LOAD_DLL                32830
#define IDS_ERR_DLL_FUNCS_NOT_FOUND     32831
#define IDS_ERR_DLL                     32832
#define IDS_ERR_DLL_CHANNELS            32833
#define IDS_DIAG_PP_NORM                32834
#define IDS_DIAG_PP_TACHY               32835
#define IDS_DIAG_PP_BRADY               32836
#define IDS_DIAG_PP_MXNS                32837
#define IDS_DIAG_PP_GOO                 32838
#define IDS_DIAG_PP_RPD                 32839
#define IDS_DIAG_PP_UGR                 32840
#define IDS_DIAG_PP_PROB_NORM           32841
#define IDS_DIAG_PP_PROB_TACHY          32842
#define IDS_DIAG_PP_POS_TACHY_CC        32843
#define IDS_DIAG_PP_POS_BRADY_CC        32844
#define IDS_DIAG_PP_SUB_PROB            32845
#define IDS_MIN_INCL_ART                32846
#define IDS_ERR_MEM_ALLOC               32847
#define IDS_ERR_EGG_READ                32848
#define IDS_SECONDS                     32849
#define IDS_EGG                         32850
#define IDS_RESPIRATION                 32851
#define IDS_MINUTES                     32852
#define IDS_START_MINUTE_OUT_OF_RANGE   32853
#define IDS_END_MINUTE_OUT_OF_RANGE     32854
#define IDS_NEED_4_MINUTES              32855
#define IDS_START_MINUTE_FORMAT_ERR     32856
#define IDS_END_MINUTE_FORMAT_ERR       32857
#define IDS_OVERWRITE_FILE              32858
#define IDS_ERR_CREATE_FILE             32859
#define IDS_ERR_WRITE_FILE              32860
#define IDS_NEED_FIRST_NAME             32861
#define IDS_NEED_LAST_NAME              32862
#define IDS_INVALID_DATE                32863
#define IDS_PATIENT_IN_DB_CONTINUE      32864
#define IDS_BAD_BATTERY                 32865
#define IDS_LOW_BATTERY                 32866
#define IDS_BAD_POS_IMPEDANCE           32867
#define IDS_BAD_NEG_IMPEDANCE           32868
#define IDS_CONTINUE                    32869
#define IDS_SUMM_BRADY_TITLE            32870
#define IDS_1_25CPM                     32871
#define IDS_25_375CPM                   32872
#define IDS_375_100CPM                  32873
#define IDS_100_150CPM                  32874
#define IDS_CONTROL                     32875
#define IDS_PATIENT                     32876
#define IDS_BL                          32877
#define IDS_MIN_10                      32878
#define IDS_MIN_20                      32879
#define IDS_MIN_30                      32880
#define IDS_SUMM_NORMAL_TITLE           32881
#define IDS_SUMM_TACHY_TITLE            32882
#define IDS_SUMM_DUOD_TITLE             32883
#define IDS_PERCENTAGE                  32884
#define IDS_WANT_TO_SAVE_PATIENT        32885
#define IDS_BRADY                       32886
#define IDS_NORMAL                      32887
#define IDS_TACHY                       32888
#define IDS_DUOD                        32889
#define IDS_PERIOD                      32890
#define IDS_ENTIRE_RANGE                32891
#define IDS_DS_DIST_AVG_PWR_15_50       32892
#define IDS_DS_DIST_AVG_PWR_15_50_1     32893
#define IDS_DS_DIST_AVG_PWR_RNG         32894
#define IDS_ERR_INVALID_HDR1            32895
#define IDS_ERR_INVALID_HDR             32895
#define IDS_WATER_INGESTED              32896
#define IDS_SIGNAL_NOT_STABLE           32897
#define IDS_EXPIRED                     32898
#define IDS_DS_RATIO_AVG_PWR            32899
#define IDS_DS_RATIO_AVG_PWR1           32900
#define IDS_1_15CPM                     32900
#define IDS_DS_AVG_DOM_FREQ             32901
#define IDS_DS_AVG_DOM_FREQ1            32902
#define ID_GOTO_CURRENT_PERIOD          32903
#define IDS_DS_PCT_DOM_FREQ1            32904
#define IDS_DIAG_DUOD_HYPER             32905
#define IDS_OPEN_SCREEN_NOTICE          32906
#define IDS_WATER_INGESTION_PHASE       32907
#define IDS_1_MIN_BET_LINES             32908
#define IDS_PATIENT_NAME                32909
#define IDS_DATE_OF_STUDY               32910
#define IDS_ATTENDING_PHYSICIAN         32911
#define IDS_REFERING_PHYSICIAN          32912
#define IDS_TECHNICIAN                  32913
#define IDS_INDICATIONS                 32914
#define IDS_NAUSEA                      32915
#define IDS_VOMITING                    32916
#define IDS_BLOATING                    32917
#define IDS_GERD                        32918
#define IDS_ERUCTUS                     32919
#define IDS_EARLY_SATEITY               32920
#define IDS_PP_FULLNESS                 32921
#define IDS_DIAGNOSIS                   32922
#define IDS_RECOMMENDATIONS             32923
#define IDS_SIGNATURE                   32924
#define IDS_DATE                        32925
#define IDS_PAGE_NUMBER                 32926
#define IDS_ERR_OPEN_FILE1              32927
#define IDS_ERROR1                      32928
#define IDS_DS_PCT_DOM_FREQ             32929
#define IDS_PM                          32930
#define IDS_AM                          32931
#define IDS_VOLTS                       32932
#define ID_FILE_BACKUP                  32934
#define IDS_BASELINE                    32935
#define IDS_FIRST_10_MIN_PD             32936
#define IDS_SECOND_10_MIN_PD            32937
#define IDS_THIRD_10_MIN_PD             32938
#define IDS_DIAG_PP_PROB_BRADY          32939
#define IDS_BACKUP_ERROR                32940
#define IDS_PUT_IN_DISK                 32941
#define IDS_PUT_IN_NEW_DISK             32942
#define IDS_DISK_TRY_AGAIN              32943
#define ID_EDIT_RESPIRATION             32944
#define ID_VIEW_RESPIRATION             32945
#define ID_VIEW_RSA                     32946
#define ID_VIEW_SUMM_GRAPH              32947
#define ID_VIEW_DATA_SHEET              32948
#define IDS_COPY_ERR_CONTINUE           32949
#define IDS_PROGRESS_BACKUP             32950
#define IDS_PROGRESS_RESTORE            32951
#define ID_EDIT_STIM_MEDIUM             32951
#define IDS_BACKUP_SUCCESS              32952
#define ID_VIEW_STIM_MEDIUM             32952
#define IDS_RESTORE_SUCCESS             32953
#define IDS_BACKUP_FAIL                 32954
#define ID_GOTO_PREVIOUS_STIM_PERIOD    32954
#define IDS_RESTORE_FAIL                32955
#define IDS_BACKUP_TO                   32956
#define ID_GOTO_NEXT_STIM_PERIOD        32956
#define IDS_RESTORE_FROM                32957
#define IDS_RESTORE_RESTART             32958
#define IDS_SQL_ERROR                   32959
#define ID_VIEW_MIN_PER_GRAPH           32959
#define IDS_SQL_INVALID_HANDLE          32960
#define IDS_FMT_DATABASE_ERROR          32961
#define IDS_FOURTH_10_MIN_PD            32962
#define IDS_MEDICATION                  32963
#define IDS_ERR_PRINTER_INIT            32964
#define IDS_ERR_PRINTER_START_PAGE      32965
#define IDS_ALL_RIGHTS_RESERVED         32966
#define IDS_ERR_READ_BATTERY_TIMEOUT    32967
#define IDS_ERR_READ_NEG_IMP_TIMEOUT    32968
#define IDS_ERR_READ_POS_IMP_TIMEOUT    32969
#define IDS_NEED_RSCH_REF_NUM           32970
#define IDS_FREQ_CPM                    32971
#define IDS_TIME                        32972
#define IDS_CORE_RPT_SELECTED           32973
#define IDS_REF_NUM                     32974
#define IDS_DELAYED_GASTRIC_EMPTYING    32975
#define IDS_READING_ZERO_POINTS         32976
#define IDS_PERIOD_X                    32977
#define IDS_POST_STIM_PERIOD            32978
#define IDS_ENTER_TYPE_MED_QTY          32979
#define IDS_TYPE_MED_QTY                32980
#define IDS_STOP_BASELINE               32981
#define IDS_STIMULATION_MEDIUM          32982
#define IDS_STOP_CONTINUE_BASELINE      32983
#define IDS_PAUSE_CONTINUE_BASELINE     32984
#define IDS_START_MIN_IN_PREV_PERIOD    32985
#define IDS_END_MIN_IN_NEXT_PERIOD      32986
#define IDS_INV_STUDY_FOR_VERSION       32987
#define IDS_ASK_DELETE_PERIOD           32988
#define IDS_INSERT_PERIOD_NO_MINUTES    32989
#define IDS_MAX_PERIODS_REACHED         32990
#define IDS_THIS_PERIOD_MUST_BE_ANALYZED 32991
#define IDS_PREV_PERIOD_MUST_BE_ANALYZED 32992
#define IDS_CHG_RESP_NOT_SET            32993
#define IDS_RESP_NOT_SAVED              32994
#define ID_FILE_RESUME_STUDY            32995
#define ID_EDIT_STIMULATION_MEDIUM      32996
#define ID_VIEW_STIMULATION_MEDIUM      32997
#define IDS_STRING32998                 32998
#define IDS_STIMULATION_MEDIUM_PHASE    32998
#define ID_REPORT_CREATESPREADSHEETOFDATASHEET 32999
#define IDS_SQL_ERR_UNKNOWN             33000
#define IDS_SS_LEFT_TITLE_1             33001
#define IDS_SS_LEFT_TITLE_2             33002
#define IDS_SS_LEFT_TITLE_3             33003
#define IDS_SS_LEFT_TITLE_4             33004
#define IDS_SS_LEFT_TITLE_5             33005
#define IDS_SS_LEFT_TITLE_6             33006
#define IDS_SS_LEFT_TITLE_7             33007
#define IDS_SS_LEFT_TITLE_8             33008
#define IDS_SS_LEFT_TITLE_9             33009
#define IDS_SS_LEFT_TITLE_10            33010
#define IDS_SS_LEFT_TITLE_11            33011
#define IDS_SS_FILE_CREATED             33012
#define IDS_ASK_DELETE_EVENT            33013
#define ID_VIEW_EVENTS                  33014
#define IDS_RESUME_TO_CONTINUE          33015
#define IDS_INFORMATION                 33016
#define IDS_STANDARD                    33017
#define IDS_RESEARCH                    33018
#define ID_EDIT_WHAT_IF                 33019
#define IDS_WANT_TO_SAVE_WHATIF         33020
#define IDS_FAILED_TO_SAVE_WHATIF       33021
#define IDS_ENTER_DESCRIPTION           33022
#define IDS_SURE_OVERWRITE_WHATIF       33023
#define IDS_DATE_TIME                   33024
#define IDS_DESCRIPTION                 33025
#define IDS_SELECT_WHATIF               33026
#define IDS_ASK_DELETE_WHATIF           33027
#define IDS_CANT_DELETE_ORIG_STUDY      33028
#define IDS_SELECT_WHATIF_LIST          33029
#define IDS_WHATIF_ORIGINAL_STUDY       33030
#define IDS_WHATIF_NEW                  33031
#define IDS_CANT_NAME_WHATIF            33032
#define IDS_GOOD_MINUTES_UNCHECKED      33033
#define IDS_PERIOD_LENGTH_UNCHECKED     33034
#define IDS_RESET_PERIODS_QUESTION      33035
#define IDS_NO_STIM_MEDIUM              33036
#define IDS_0_300                       33037
#define IDS_325_600                     33038
#define IDS_625_1500                    33039
#define IDS_0_15                        33040
#define ID_FILE_EXPORT_STUDIES          33041
#define ID_FILE_IMPORTSTUDIES           33042
#define IDS_SEL_READER_DB               33043
#define IDS_OVERWRITE_PATIENT           33044
#define IDS_FILE_COPY_ERR               33045
#define IDS_OVERWRITE_STUDY             33046
#define IDS_IMPORT_PROGRESS             33047
#define IDS_IMPORT_COMPLETE             33048
#define IDS_SEL_REMOTE_DB_LOC           33049
#define IDS_IMPORT_CANCELLED            33050
#define IDS_IMPORT_FAILED               33051
#define IDS_STRING33052                 33052
#define IDS_ADD_EXT_STUDIES_SURE        33052
#define ID_HELP_ABOUT_READER            33053
#define IDS_DB_NOT_FOUND                33054
#define ID_HELP_ABOUT3CPMEGGSASCENTRALDATADEPOTREADER 33055
#define IDS_SELECT_STUDY_FROM_LIST      33056
#define IDS_DB_VERSION_WRONG            33057
#define IDS_DB_ACCESS_ERR               33058
#define IDS_CONTACT_SUPPORT             33059
#define IDS_INV_FILE_HDR                33060
#define IDS_BCKUP_COMP_ERRS             33061
#define IDS_REST_COMP_ERRS              33062
#define IDS_BACKUP_ERRORS               33063
#define IDS_BACKUP_ERRORS_NUM           33064
#define IDS_RESTORE_ERRORS              33065
#define IDS_RESTORE_ERRORS_NUM          33066
#define IDS_DATA_FILE_MISSING           33067
#define IDS_BCKUP_DATA_FILE_MISSING     33068
#define IDS_EXPIRE_DATE                 33069
#define IDS_DEMO_OPEN_SCREEN_NOTICE     33070
#define ID_FILE_SAVERAWDATAINASCII      33071
#define ID_FILE_SAVERAWDATAINASCII33072 33072
#define IDS_ENTER_FILE_NAME             33073
#define ID_SETTINGS                     33074
#define ID_SETTINGS33077                33077
#define ID_Menu                         33078
#define ID_SETTINGS_FREQUENCYRANGE      33079
#define ID_VIEW_FILTER_RSA              33082
#define ID_SETTINGS_FILTERRSA           33083
#define ID_VIEW_VIEWHIDDENPATIENTFILES  33084
#define ID_REPORT_SHOW                  33090
#define ID_REPORT_SHOW33091             33091
#define ID_Menu33092                    33092
#define ID_REPORT_SHOW33093             33093

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         33094
#define _APS_NEXT_CONTROL_VALUE         1313
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
